USE [master]
GO
/****** Object:  Database [Global]    Script Date: 26/03/2019 1:56:35 p. m. ******/
CREATE DATABASE [Global] ON  PRIMARY 
( NAME = N'Global', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Global.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Global_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\Global_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Global].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Global] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Global] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Global] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Global] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Global] SET ARITHABORT OFF 
GO
ALTER DATABASE [Global] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Global] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Global] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Global] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Global] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Global] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Global] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Global] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Global] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Global] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Global] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Global] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Global] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Global] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Global] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Global] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Global] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Global] SET  MULTI_USER 
GO
ALTER DATABASE [Global] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Global] SET DB_CHAINING OFF 
GO
USE [Global]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 26/03/2019 1:56:35 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[Address] [varchar](50) NULL,
	[Phone] [varchar](15) NULL,
	[Email] [varchar](50) NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [Global] SET  READ_WRITE 
GO
